import assert from 'node:assert/strict';
import { WORKS, WORK_BY_ID, PREFAB_H_PER_ML, TRUCK_8X4_DEFAULT, FIBRES, CHIMNEY_CONDUITS, CHIMNEY_STACKS, CHIMNEY_CAPS } from './references.js';
assert.equal(WORKS.length,40);
assert.equal(TRUCK_8X4_DEFAULT,800);
assert.equal(PREFAB_H_PER_ML.standard,1.55);
assert.equal(PREFAB_H_PER_ML.hauteur_importante,1.9);
assert.equal(PREFAB_H_PER_ML.lourd_complexe,2.75);
assert.deepEqual([FIBRES.courante.min,FIBRES.courante.max],[3,4]);
assert.deepEqual([FIBRES.renforcee.min,FIBRES.renforcee.max],[5,6]);
assert.deepEqual([FIBRES.fortement_sollicitee.min,FIBRES.fortement_sollicitee.max],[7,9]);
assert.deepEqual([FIBRES.metallique_structurelle.min,FIBRES.metallique_structurelle.max],[20,40]);
const semelleVol=30*(60/100)*(30/100); assert.equal(semelleVol,5.3999999999999995);
assert.equal(WORK_BY_ID.semelle_filante.acierParUnite,50);
assert.equal(WORK_BY_ID.chainage_horizontal.moHParUnite,0.35);
assert.equal(CHIMNEY_CONDUITS['20x20'].h,0.75);
assert.equal(CHIMNEY_STACKS.simple.h,3.5);
assert.equal(CHIMNEY_CAPS.standard.h,1);
const chimneyHours=5*CHIMNEY_CONDUITS['20x20'].h+CHIMNEY_STACKS.simple.h+CHIMNEY_CAPS.standard.h;
assert.equal(chimneyHours,8.25);
const hh=16,workers=2; assert.equal(hh/workers,8);
console.log('OK — 40 ouvrages + semelle + préfabriqué + fibres + cheminée + heures-homme/durée');
