const API = window.SpeedArtiPlaquisteReal || {};
const RULES = API.rules || {};
const ABAQUE = API.abaque || [];
const R = {
  plateLossWall: RULES.plaques?.perteMurPct ?? 7,
  plateLossCeiling: RULES.plaques?.pertePlafondPct ?? 10,
  plateLossRampant: RULES.plaques?.perteRampantPct ?? 12,
  frameLoss: RULES.ossature?.pertePct ?? 5,
  screwsWall: RULES.vis?.premierePeauMurParM2 ?? 25,
  screwsCeiling: RULES.vis?.premierePeauPlafondParM2 ?? 18,
  screwsSecond: RULES.vis?.secondePeauParM2 ?? 20,
  screwsLoss: RULES.vis?.pertePct ?? 10,
  screwsBox: RULES.vis?.boiteUnites ?? 500,
  finishBandWall: RULES.finitions?.bandeMurMlM2 ?? 1.8,
  finishBandCeiling: RULES.finitions?.bandePlafondMlM2 ?? 2.2,
  finishCompoundWall: RULES.finitions?.enduitMurKgM2 ?? 0.5,
  finishCompoundCeiling: RULES.finitions?.enduitPlafondKgM2 ?? 0.6,
  finishPrices: RULES.finitions?.prixVenteHtM2 ?? {aucune:0,bandes:5,pret_a_peindre:9,soignee:13},
  impression: RULES.finitions?.impressionHtM2 ?? 5,
  isoLoss: RULES.isolation?.pertePanneauxRouleauxPct ?? 10,
  isoBlownLoss: RULES.isolation?.perteSoufflePct ?? 3,
  semiRigidMaterial: RULES.isolation?.semiRigideCoefMatiere ?? 1.2,
  semiRigidLabor: RULES.isolation?.semiRigideCoefMainOeuvre ?? 1.2,
  secondLayerSale: RULES.isolation?.secondeCouchePoseHtM2 ?? 3,
  crossedLabor: RULES.isolation?.poseCroiseeCoefMainOeuvre ?? 1.15,
  pareVapeur: RULES.isolation?.pareVapeurPrixVenteHtM2 ?? 3.5,
  freinVapeur: RULES.isolation?.freinVapeurPrixVenteHtM2 ?? 5,
  cloisonLabor: RULES.mainOeuvre?.cloisonHParM2 ?? .35,
  doublageOptimaLabor: RULES.mainOeuvre?.doublageOptimaHParM2 ?? .40,
  doublageClassicNoIsoLabor: RULES.mainOeuvre?.doublageClassiqueSansIsolantHParM2 ?? .26,
  doublageClassicIsoLabor: RULES.mainOeuvre?.doublageClassiqueAvecIsolantHParM2 ?? .32,
  ceilingLabor: RULES.mainOeuvre?.plafondDroitHParM2 ?? .40,
  secondSkinLabor: RULES.mainOeuvre?.secondePeauHParM2 ?? .05,
  highHeight: RULES.optionsDirectes?.seuilGrandeHauteurM ?? 3.5,
  highHeightSale: RULES.optionsDirectes?.grandeHauteurHtM2 ?? 4,
  cutsSale: RULES.optionsDirectes?.nombreusesDecoupesSpotsHtM2 ?? 2,
  rampantSale: RULES.optionsDirectes?.rampantHtM2 ?? 5,
  rampantComplexSale: RULES.optionsDirectes?.rampantComplexeHtM2 ?? 11,
  reprise: RULES.optionsDirectes?.repriseExistantHt ?? 150,
  access: RULES.optionsDirectes?.accesDifficileHt ?? 450,
  optima: {
    furring: RULES.optima?.fourrureF530MlM2 ?? 1.8,
    clip: RULES.optima?.lisseClipMlM2 ?? .9,
    support: RULES.optima?.appuiUniteM2 ?? .75,
    key: RULES.optima?.cleUniteM2 ?? .75,
    fixingPerRow: RULES.optima?.fixationsUniteM2ParRangee ?? 2,
  }
};
const PLATES = {
  BA13: {label:'BA13 standard', surcharge:0},
  hydro: {label:'BA13 hydrofuge', surcharge:.85},
  phonique: {label:'BA13 phonique', surcharge:1.35},
  feu: {label:'BA13 feu', surcharge:2},
  habito: {label:'Habito', surcharge:3.20},
};
const PROFILES = {
  '48/50': {label:'48 mm', width:48, railPrice:1.80, studPrice:2.10},
  '72/50': {label:'72 mm', width:72, railPrice:0, studPrice:0},
  '100/50': {label:'100 mm', width:100, railPrice:0, studPrice:0},
};
const COMPLEXITY = {simple:.9,moyenne:1,complexe:1.3};
const STORE = 'speedarti-plaquiste-demo-independent-walls-v110';
const steps = [
  ['Chantier','Contexte & TVA'],['Ouvrages','Pièces & murs simples'],['Murs','Configuration indépendante'],
  ['Plafonds','Droit / rampant'],['Options','Finitions & forfaits'],['Résultats','Calcul détaillé']
];
let step = 0;
let selected = {};
let state = load() || createInitial();
const $ = (s) => document.querySelector(s);
const content = $('#content');
$('#prev').onclick = () => go(step-1);
$('#next').onclick = () => step===5 ? renderResults() : go(step+1);
$('#saveBtn').onclick = () => save(true);
$('#calcBtn').onclick = () => { step=5; render(); };
$('#steps').addEventListener('click', e => { const b=e.target.closest('[data-step]'); if(b) go(+b.dataset.step); });
content.addEventListener('click', onClick);
content.addEventListener('change', onInput);
content.addEventListener('input', onInput);
render();

function uid(){ return crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2)+Date.now(); }
function isoDefault(){ const ref = ABAQUE.find(x => /cloison/i.test(x.usage)) || ABAQUE[0]; return {active:false,reference:ref?.id||'',price:ref?.prixAchatHtM2||0,thickness:ref?.epaisseurMm||45,semiRigid:false,doubleLayer:false,secondReference:ref?.id||'',crossed:false,pareVapeur:false,freinVapeur:false,validated:false}; }
function faceDefault(){ return {plate:'BA13',doubleSkin:false}; }
function framingDefault(){ return {profile:'48/50',spacingCm:60,system:'classique',optimaRows:null,doubledStuds:false}; }
function wallBase(id,label,length){ return {id,label,active:true,type:'cloison',length:+length||1,framing:framingDefault(),isolation:isoDefault(),face1:faceDefault(),face2:faceDefault(),openings:[],reinforcementQty:0,reinforcementPrice:75}; }
function makePiece(n=1){ const L=5,W=4; return {id:uid(),name:`Pièce ${n}`,length:L,width:W,height:2.5,walls:[wallBase('A','Mur A (face)',L),wallBase('B','Mur B (droite)',W),wallBase('C','Mur C (fond)',L),wallBase('D','Mur D (gauche)',W)],ceiling:{active:true,type:'droit',manualArea:null,face:faceDefault(),isolation:isoDefault()}}; }
function makeSimpleWall(n=1){ const w=wallBase(uid(),`Mur simple ${n}`,4); w.height=2.5; return w; }
function createInitial(){ return {project:{name:'Chiffrage Plaquiste — démo',olderThan2Years:true},pieces:[makePiece(1)],simpleWalls:[],options:{hourlyRate:45,workers:1,materialMargin:0,complexity:'moyenne',finish:'bandes',impression:false,reprise:false,reprisePrice:R.reprise,access:false,accessPrice:R.access,cuts:false,extras:[]}}; }
function load(){ try{return JSON.parse(localStorage.getItem(STORE));}catch{return null;} }
function save(show=false){ localStorage.setItem(STORE,JSON.stringify(state)); if(show) toast('Brouillon enregistré'); }
function go(n){ step=Math.max(0,Math.min(5,n)); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function render(){ $('#steps').innerHTML=steps.map((s,i)=>`<button class="step ${i===step?'active':''}" data-step="${i}"><b>${i+1}. ${s[0]}</b><span>${s[1]}</span></button>`).join(''); $('#prev').style.visibility=step?'visible':'hidden'; $('#next').textContent=step===5?'Recalculer':'Suivant →'; [renderProject,renderWorks,renderWalls,renderCeilings,renderOptions,renderResults][step](); }
function head(k,t,p){ return `<div class="head"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></div>`; }

function renderProject(){ content.innerHTML = head('Étape 1','Contexte du chantier','Le choix de l’ancienneté du logement sera réutilisable pour tous les métiers et sert ici à la logique TVA à valider fiscalement.') + `
<div class="card"><div class="grid"><div class="field c6"><label>Nom du chiffrage</label><input class="input" data-path="project.name" value="${esc(state.project.name)}"></div><div class="field c3"><label>Taux horaire HT</label><input class="input" type="number" step="1" data-path="options.hourlyRate" value="${state.options.hourlyRate}"></div><div class="field c3"><label>Marge matériaux (%)</label><input class="input" type="number" step=".1" data-path="options.materialMargin" value="${state.options.materialMargin}"></div></div>
<div class="choice-grid"><button class="choice-card ${state.project.olderThan2Years?'selected':''}" data-age="old"><b>🏠 Logement + de 2 ans</b><span>Rénovation : taux réduits selon la prestation.</span></button><button class="choice-card ${!state.project.olderThan2Years?'selected':''}" data-age="new"><b>🏗️ Logement - de 2 ans / neuf</b><span>TVA 20 % dans cette démo.</span></button></div>
<div class="alert warn"><b>Important :</b> la sélection automatique de TVA reprend la règle métier demandée par Guillaume. La conformité fiscale sera contrôlée séparément avant production.</div></div>`; }

function renderWorks(){ let html=head('Étape 2','Pièces et murs simples','Le mode Linéaire est supprimé. Une pièce et plusieurs murs simples peuvent désormais cohabiter dans le même chiffrage.');
html += `<div class="row between toolbar"><h2>Ouvrages</h2><div class="row"><button class="btn secondary" data-action="add-piece">+ Ajouter une pièce</button><button class="btn primary" data-action="add-simple">+ Ajouter un mur simple</button></div></div>`;
html += state.pieces.map((p,i)=>`<div class="card"><div class="row between"><div><h2>${esc(p.name)}</h2><span class="muted">Pièce complète avec murs A/B/C/D indépendants</span></div><button class="btn danger small" data-action="remove-piece" data-id="${p.id}">Supprimer</button></div><div class="grid"><div class="field c4"><label>Nom</label><input class="input" data-piece="${p.id}" data-pkey="name" value="${esc(p.name)}"></div><div class="field c2"><label>Longueur (m)</label><input class="input" type="number" step=".1" data-piece="${p.id}" data-pkey="length" value="${p.length}"></div><div class="field c2"><label>Largeur (m)</label><input class="input" type="number" step=".1" data-piece="${p.id}" data-pkey="width" value="${p.width}"></div><div class="field c2"><label>Hauteur (m)</label><input class="input" type="number" step=".1" data-piece="${p.id}" data-pkey="height" value="${p.height}"></div><div class="field c2"><label>Plafond</label><select class="select" data-piece="${p.id}" data-pkey="ceiling.active"><option value="true" ${p.ceiling.active?'selected':''}>Oui</option><option value="false" ${!p.ceiling.active?'selected':''}>Non</option></select></div></div></div>`).join('');
html += state.simpleWalls.map((w,i)=>`<div class="card simple-card"><div class="row between"><div><h2>${esc(w.label)}</h2><span class="muted">Mur indépendant, cumulable avec les pièces</span></div><button class="btn danger small" data-action="remove-simple" data-id="${w.id}">Supprimer</button></div><div class="grid"><div class="field c5"><label>Nom</label><input class="input" data-simple="${w.id}" data-skey="label" value="${esc(w.label)}"></div><div class="field c3"><label>Longueur (m)</label><input class="input" type="number" step=".1" data-simple="${w.id}" data-skey="length" value="${w.length}"></div><div class="field c3"><label>Hauteur (m)</label><input class="input" type="number" step=".1" data-simple="${w.id}" data-skey="height" value="${w.height}"></div></div></div>`).join('');
if(!state.simpleWalls.length) html += `<div class="note-card">💡 « Ajouter un mur simple » remplace définitivement l’ancien mode Linéaire.</div>`;
content.innerHTML=html; }

function renderWalls(){ let html=head('Étape 3','Configuration indépendante de chaque mur','Chaque mur possède sa propre ossature, sa propre isolation et ses propres parements. Un réglage sur un mur ne modifie jamais les autres.');
state.pieces.forEach(p=>{ syncPieceWalls(p); const sel=selected[p.id] || 'A'; selected[p.id]=sel; const wall=p.walls.find(w=>w.id===sel) || p.walls[0]; html += `<div class="card"><div class="row between"><div><h2>${esc(p.name)}</h2><span class="muted">Cliquez sur A, B, C ou D puis configurez uniquement ce mur.</span></div><span class="status-chip">Mur sélectionné : ${esc(wall.id)}</span></div><div class="piece-layout"><div><div class="plan">${planSvg(p,sel)}</div><div class="legend"><span><i class="dot" style="background:#3b82f6"></i> Cloison</span><span><i class="dot" style="background:#f59e0b"></i> Doublage</span><span><i class="dot" style="background:#94a3b8"></i> Inactif</span></div></div><div>${wallEditor(wall,p.height,`piece:${p.id}`)}</div></div></div>`; });
if(state.simpleWalls.length){ html += `<h2 class="section-title">Murs simples</h2>`; state.simpleWalls.forEach(w=>{ html += `<div class="card"><div class="row between"><h2>${esc(w.label)}</h2><span class="status-chip">Mur simple</span></div>${wallEditor(w,w.height,`simple:${w.id}`,true)}</div>`; }); }
content.innerHTML=html; }

function wallEditor(w,height,scope,isSimple=false){ const iso=ensureIso(w); const f1=ensureFace(w,'face1'); const f2=ensureFace(w,'face2'); const profile=PROFILES[w.framing.profile]||PROFILES['48/50']; const suggestion=suggestRows(height); const net=wallNet(w,height); const secondFace=w.type==='cloison'; return `<div class="wall-editor"><div class="grid"><div class="field c3"><label>Actif</label><select class="select" data-wall="${scope}" data-wkey="active"><option value="true" ${w.active?'selected':''}>Oui</option><option value="false" ${!w.active?'selected':''}>Non</option></select></div><div class="field c5"><label>Type de mur</label><select class="select" data-wall="${scope}" data-wkey="type"><option value="cloison" ${w.type==='cloison'?'selected':''}>Cloison — 2 faces</option><option value="doublage" ${w.type==='doublage'?'selected':''}>Doublage — 1 face</option></select></div>${isSimple?`<div class="field c4"><label>Hauteur (m)</label><input class="input" type="number" step=".1" data-wall="${scope}" data-wkey="height" value="${height}"></div>`:''}</div>
<div class="subcard"><h3>1. Ossature de ce mur</h3><div class="grid"><div class="field c4"><label>Profil</label><select class="select" data-wall="${scope}" data-wkey="framing.profile">${Object.entries(PROFILES).map(([k,p])=>`<option value="${k}" ${w.framing.profile===k?'selected':''}>${p.label}</option>`).join('')}</select></div><div class="field c4"><label>Entraxe montants</label><select class="select" data-wall="${scope}" data-wkey="framing.spacingCm"><option value="60" ${+w.framing.spacingCm===60?'selected':''}>60 cm</option><option value="40" ${+w.framing.spacingCm===40?'selected':''}>40 cm</option></select></div><div class="field c4"><label>Système doublage</label><select class="select" data-wall="${scope}" data-wkey="framing.system" ${w.type!=='doublage'?'disabled':''}><option value="classique" ${w.framing.system==='classique'?'selected':''}>Classique</option><option value="optima" ${w.framing.system==='optima'?'selected':''}>Optima</option></select></div></div><div class="row wrap"><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="framing.doubledStuds" ${w.framing.doubledStuds?'checked':''}> Montants doublés</label>${w.type==='doublage'&&w.framing.system==='optima'?`<div class="field compact"><label>Rangées appuis Optima</label><input class="input" type="number" min="1" data-wall="${scope}" data-wkey="framing.optimaRows" value="${w.framing.optimaRows||suggestion}"><span class="hint">Suggestion automatique : ${suggestion} selon ${fmt(height)} m</span></div>`:''}</div><div class="hint">Épaisseur profil : ${profile.width} mm. Ossature calculée uniquement pour ce mur.</div></div>
<div class="subcard"><h3>2. Isolation de ce mur</h3>${isoEditor(iso,scope,net,profile.width)}</div>
<div class="faces-grid"><div class="subcard"><h3>3. Face 1</h3>${faceEditor(f1,scope,'face1')}</div>${secondFace?`<div class="subcard"><h3>4. Face 2</h3>${faceEditor(f2,scope,'face2')}</div>`:`<div class="subcard muted-box"><h3>Face 2</h3><p>Non applicable : un doublage possède une seule face de parement.</p></div>`}</div>
<div class="subcard"><div class="row between"><h3>Ouvertures de ce mur</h3><button class="btn secondary small" data-action="add-opening" data-scope="${scope}">+ Ajouter</button></div>${(w.openings||[]).map(o=>openingRow(o,scope)).join('')||`<div class="note">Aucune ouverture.</div>`}<div class="grid top-gap"><div class="field c4"><label>Renforts OSB</label><input class="input" type="number" min="0" data-wall="${scope}" data-wkey="reinforcementQty" value="${w.reinforcementQty||0}"></div><div class="field c4"><label>Prix unitaire HT</label><input class="input" type="number" step="1" data-wall="${scope}" data-wkey="reinforcementPrice" value="${w.reinforcementPrice??75}"></div><div class="field c4"><label>Surface nette 1 face</label><input class="input" disabled value="${fmt(net)} m²"></div></div></div></div>`; }
function faceEditor(face,scope,key){ return `<div class="grid"><div class="field c7"><label>Type de plaque</label><select class="select" data-wall="${scope}" data-wkey="${key}.plate">${Object.entries(PLATES).map(([k,p])=>`<option value="${k}" ${face.plate===k?'selected':''}>${p.label}</option>`).join('')}</select></div><div class="field c5"><label>Peaux</label><select class="select" data-wall="${scope}" data-wkey="${key}.doubleSkin"><option value="false" ${!face.doubleSkin?'selected':''}>Simple peau</option><option value="true" ${face.doubleSkin?'selected':''}>Double peau</option></select></div></div><div class="hint">Cette face peut être différente de l’autre : standard, hydrofuge, phonique, feu ou Habito.</div>`; }
function isoEditor(iso,scope,surface,profileWidth){ if(!iso.active) return `<label class="check big-check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.active"> Ajouter une isolation sur ce mur</label><div class="hint">Aucune isolation n’est calculée pour ce mur.</div>`; const ref=ABAQUE.find(x=>x.id===iso.reference)||ABAQUE[0]; const second=ABAQUE.find(x=>x.id===iso.secondReference)||ref; const tooThick=(+iso.thickness||ref?.epaisseurMm||0)>profileWidth; return `<label class="check big-check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.active" checked> Isolation active</label><div class="iso-grid"><div class="field"><label>Isolant couche 1</label><select class="select" data-wall="${scope}" data-wkey="isolation.reference">${ABAQUE.map(x=>`<option value="${x.id}" ${x.id===iso.reference?'selected':''}>${esc(x.nom)} — ${x.epaisseurMm} mm — ${x.prixAchatHtM2.toFixed(2)} € achat/m²</option>`).join('')}</select></div><div class="field"><label>Épaisseur (mm)</label><input class="input" type="number" data-wall="${scope}" data-wkey="isolation.thickness" value="${iso.thickness||ref?.epaisseurMm||0}"></div><div class="field"><label>Prix achat HT/m²</label><input class="input" type="number" step=".01" data-wall="${scope}" data-wkey="isolation.price" value="${iso.price??ref?.prixAchatHtM2??0}"></div></div><div class="row wrap top-gap"><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.validated" ${iso.validated?'checked':''}> Choix validé par l’artisan</label><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.semiRigid" ${iso.semiRigid?'checked':''}> Semi-rigide ×1,20</label><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.doubleLayer" ${iso.doubleLayer?'checked':''}> Double couche</label><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.crossed" ${iso.crossed?'checked':''} ${!iso.doubleLayer?'disabled':''}> Pose croisée</label><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.pareVapeur" ${iso.pareVapeur?'checked':''}> Pare-vapeur 3,50 €/m²</label><label class="check"><input type="checkbox" data-wall="${scope}" data-wkey="isolation.freinVapeur" ${iso.freinVapeur?'checked':''}> Hygrovariable 5 €/m²</label></div>${iso.doubleLayer?`<div class="field top-gap"><label>Isolant couche 2</label><select class="select" data-wall="${scope}" data-wkey="isolation.secondReference">${ABAQUE.map(x=>`<option value="${x.id}" ${x.id===iso.secondReference?'selected':''}>${esc(x.nom)} — ${x.epaisseurMm} mm</option>`).join('')}</select></div>`:''}${tooThick?`<div class="alert warn">⚠️ L’isolant (${iso.thickness||ref?.epaisseurMm} mm) dépasse le profil (${profileWidth} mm). Alerte explicite, mais aucun blocage.</div>`:''}<div class="hint">Surface isolée de ce mur : ${fmt(surface)} m². Aucun réglage d’un autre mur n’est repris automatiquement.</div>`; }
function openingRow(o,scope){ return `<div class="open-row"><div class="field"><label>Type</label><select class="select" data-open="${o.id}" data-scope="${scope}" data-okey="type"><option value="porte" ${o.type==='porte'?'selected':''}>Porte</option><option value="fenetre" ${o.type==='fenetre'?'selected':''}>Fenêtre</option><option value="baie" ${o.type==='baie'?'selected':''}>Baie</option></select></div><div class="field"><label>Largeur</label><input class="input" type="number" step=".01" data-open="${o.id}" data-scope="${scope}" data-okey="width" value="${o.width}"></div><div class="field"><label>Hauteur</label><input class="input" type="number" step=".01" data-open="${o.id}" data-scope="${scope}" data-okey="height" value="${o.height}"></div><div class="field"><label>Qté</label><input class="input" type="number" min="1" data-open="${o.id}" data-scope="${scope}" data-okey="qty" value="${o.qty}"></div><button class="btn danger small" data-action="remove-opening" data-scope="${scope}" data-openid="${o.id}">×</button></div>`; }

function renderCeilings(){ let html=head('Étape 4','Plafonds indépendants par pièce','Chaque pièce possède son propre plafond. Les rampants sont chiffrés comme plus-value simplifiée, conformément à la décision métier.'); if(!state.pieces.some(p=>p.ceiling.active)) html+=`<div class="note-card">Aucun plafond actif.</div>`; state.pieces.forEach(p=>{ const c=p.ceiling; if(!c.active) return; const area=ceilingArea(p); const iso=c.isolation||isoDefault(); c.isolation=iso; html += `<div class="card"><div class="row between"><div><h2>${esc(p.name)} — plafond</h2><span class="muted">Surface utilisée : ${fmt(area)} m²</span></div><label class="check"><input type="checkbox" data-ceiling="${p.id}" data-ckey="active" ${c.active?'checked':''}> Actif</label></div><div class="grid"><div class="field c4"><label>Type</label><select class="select" data-ceiling="${p.id}" data-ckey="type"><option value="droit" ${c.type==='droit'?'selected':''}>Plafond droit</option><option value="rampant" ${c.type==='rampant'?'selected':''}>Rampant +5 €/m²</option><option value="rampant_complexe" ${c.type==='rampant_complexe'?'selected':''}>Rampant complexe +11 €/m²</option></select></div>${c.type!=='droit'?`<div class="field c4"><label>Surface réelle rampant (m²)</label><input class="input" type="number" step=".1" data-ceiling="${p.id}" data-ckey="manualArea" value="${c.manualArea??(p.length*p.width)}"></div>`:`<div class="field c4"><label>Surface auto</label><input class="input" disabled value="${fmt(p.length*p.width)} m²"></div>`}<div class="field c4"><label>Parement</label><select class="select" data-ceiling="${p.id}" data-ckey="face.plate">${Object.entries(PLATES).map(([k,v])=>`<option value="${k}" ${c.face.plate===k?'selected':''}>${v.label}</option>`).join('')}</select></div></div><div class="row wrap top-gap"><label class="check"><input type="checkbox" data-ceiling="${p.id}" data-ckey="face.doubleSkin" ${c.face.doubleSkin?'checked':''}> Double peau</label><label class="check"><input type="checkbox" data-ceiling="${p.id}" data-ckey="isolation.active" ${iso.active?'checked':''}> Isolation plafond</label></div>${iso.active?`<div class="subcard top-gap"><h3>Isolation plafond de cette pièce</h3>${ceilingIsoEditor(iso,p.id,area)}</div>`:''}${c.type!=='droit'?`<div class="alert warn">⚠️ Rampant : la plus-value s’ajoute au plafond de base. L’ossature supplémentaire spécifique au rampant n’est pas recalculée dans cette version simplifiée.</div>`:''}</div>`; }); content.innerHTML=html; }
function ceilingIsoEditor(iso,pid,area){ const ref=ABAQUE.find(x=>x.id===iso.reference)||ABAQUE[0]; return `<div class="iso-grid"><div class="field"><label>Isolant</label><select class="select" data-ceiling="${pid}" data-ckey="isolation.reference">${ABAQUE.map(x=>`<option value="${x.id}" ${x.id===iso.reference?'selected':''}>${esc(x.nom)} — ${x.epaisseurMm} mm</option>`).join('')}</select></div><div class="field"><label>Épaisseur</label><input class="input" type="number" data-ceiling="${pid}" data-ckey="isolation.thickness" value="${iso.thickness||ref?.epaisseurMm||0}"></div><div class="field"><label>Prix achat HT/m²</label><input class="input" type="number" step=".01" data-ceiling="${pid}" data-ckey="isolation.price" value="${iso.price??ref?.prixAchatHtM2??0}"></div></div><div class="row wrap top-gap"><label class="check"><input type="checkbox" data-ceiling="${pid}" data-ckey="isolation.validated" ${iso.validated?'checked':''}> Validé artisan</label><label class="check"><input type="checkbox" data-ceiling="${pid}" data-ckey="isolation.semiRigid" ${iso.semiRigid?'checked':''}> Semi-rigide</label><label class="check"><input type="checkbox" data-ceiling="${pid}" data-ckey="isolation.doubleLayer" ${iso.doubleLayer?'checked':''}> Double couche</label><label class="check"><input type="checkbox" data-ceiling="${pid}" data-ckey="isolation.crossed" ${iso.crossed?'checked':''} ${!iso.doubleLayer?'disabled':''}> Pose croisée</label></div><div class="hint">Surface isolée : ${fmt(area)} m².</div>`; }

function renderOptions(){ const o=state.options; content.innerHTML=head('Étape 5','Finitions et options chantier','Les forfaits chantier restent distincts des réglages propres à chaque mur.')+`<div class="card"><h2>Finition</h2><div class="choice-grid four">${[['aucune','Sans finition'],['bandes','Bandes — 5 €/m²'],['pret_a_peindre','Prêt à peindre — 9 €/m²'],['soignee','Soignée — 13 €/m²']].map(([k,l])=>`<button class="choice-card ${o.finish===k?'selected':''}" data-finish="${k}"><b>${l}</b></button>`).join('')}</div>${(o.finish==='pret_a_peindre'||o.finish==='soignee')?`<label class="check top-gap"><input type="checkbox" data-path="options.impression" ${o.impression?'checked':''}> Impression +5 €/m² (matière + MO)</label>`:''}</div>
<div class="card"><h2>Options chantier</h2><div class="option-list"><div class="option-row"><label class="check"><input type="checkbox" data-path="options.reprise" ${o.reprise?'checked':''}> <b>Reprise sur existant</b></label><input class="input money" type="number" data-path="options.reprisePrice" value="${o.reprisePrice}"><span>€ HT / chantier</span></div><div class="option-row"><label class="check"><input type="checkbox" data-path="options.access" ${o.access?'checked':''}> <b>Accès difficile</b></label><input class="input money" type="number" data-path="options.accessPrice" value="${o.accessPrice}"><span>€ HT / chantier</span></div><div class="option-row"><label class="check"><input type="checkbox" data-path="options.cuts" ${o.cuts?'checked':''}> <b>Nombreuses découpes / spots</b></label><span>+2 € HT/m²</span></div><div class="option-row"><span><b>Complexité générale</b></span><select class="select short" data-path="options.complexity"><option value="simple" ${o.complexity==='simple'?'selected':''}>Simple</option><option value="moyenne" ${o.complexity==='moyenne'?'selected':''}>Moyenne</option><option value="complexe" ${o.complexity==='complexe'?'selected':''}>Complexe</option></select></div></div></div>
<div class="card"><div class="row between"><div><h2>Extras à prix direct</h2><span class="muted">Caisson, niche, éclairage ou autre prestation : ligne distincte, quantité et prix modifiables.</span></div><button class="btn secondary" data-action="add-extra">+ Ajouter un extra</button></div>${o.extras.map(x=>`<div class="extra-row"><input class="input" data-extra="${x.id}" data-ekey="name" value="${esc(x.name)}"><input class="input" type="number" step="1" data-extra="${x.id}" data-ekey="qty" value="${x.qty}"><input class="input" type="number" step="1" data-extra="${x.id}" data-ekey="price" value="${x.price}"><button class="btn danger small" data-action="remove-extra" data-id="${x.id}">×</button></div>`).join('')||`<div class="note">Aucun extra.</div>`}</div>`; }

function renderResults(){ const result=calculate(); content.innerHTML=head('Étape 6','Résultat détaillé','Le calcul est désormais construit mur par mur : ossature, isolation et parements sont indépendants pour chaque ouvrage.') + resultHtml(result); }
function resultHtml(r){ return `<div class="metrics"><div class="metric"><span>Surface parements</span><strong>${fmt(r.surfaces.cladding)} m²</strong></div><div class="metric"><span>Heures</span><strong>${fmt(r.laborHours)} h</strong></div><div class="metric"><span>Total HT</span><strong>${eur(r.totalHT)}</strong></div><div class="metric"><span>Total TTC</span><strong>${eur(r.totalTTC)}</strong></div></div>${r.alerts.map(a=>`<div class="alert warn">${esc(a)}</div>`).join('')}<details class="details" open><summary>Surfaces par ouvrage</summary><div class="inside table-wrap"><table class="table"><thead><tr><th>Ouvrage</th><th>Type</th><th>Surface 1 face</th><th>Parements</th><th>Isolation</th></tr></thead><tbody>${r.wallRows.map(w=>`<tr><td>${esc(w.label)}</td><td>${esc(w.type)}</td><td>${fmt(w.netOne)} m²</td><td>${fmt(w.cladding)} m²</td><td>${w.isolation?fmt(w.netOne)+' m²':'—'}</td></tr>`).join('')}</tbody></table></div></details><details class="details" open><summary>Matériaux et commandes</summary><div class="inside table-wrap"><table class="table"><thead><tr><th>Désignation</th><th>Qté calculée</th><th>Commande</th><th>PU HT</th><th>Total HT</th></tr></thead><tbody>${r.materials.map(m=>`<tr><td>${esc(m.name)}<div class="hint">${esc(m.note||'')}</div></td><td>${fmt(m.qty)} ${esc(m.unit)}</td><td>${esc(m.order||'—')}</td><td>${m.unitPrice?eur(m.unitPrice):'—'}</td><td>${m.total?eur(m.total):'—'}</td></tr>`).join('')}</tbody></table></div></details><details class="details" open><summary>Main-d’œuvre</summary><div class="inside">${r.labor.map(x=>`<div class="row between line"><span>${esc(x.name)}</span><b>${fmt(x.hours)} h</b></div>`).join('')}<div class="row between total-line"><b>Total MO</b><b>${eur(r.laborCost)}</b></div></div></details><details class="details" open><summary>Vente / forfaits</summary><div class="inside">${r.sales.map(x=>`<div class="row between line"><span>${esc(x.name)}</span><b>${eur(x.total)}</b></div>`).join('')||'<div class="note">Aucun forfait supplémentaire.</div>'}<div class="row between total-line"><b>Total HT</b><b>${eur(r.totalHT)}</b></div><div class="row between line"><span>TVA calculée par ligne</span><b>${eur(r.vat)}</b></div><div class="row between total-line"><b>Total TTC</b><b>${eur(r.totalTTC)}</b></div></div></details><div class="card"><h2>Contrôle d’indépendance des murs</h2><p class="muted">Chaque ligne ci-dessus provient de la configuration du mur concerné. Modifier l’ossature, l’isolation ou une face du Mur A ne modifie pas le Mur B, C, D ni un mur simple.</p></div>`; }

function calculate(){ const materials=[],sales=[],labor=[],alerts=[],wallRows=[]; let cladding=0,ceilingSurface=0,laborHours=0; const margin=Math.max(0,+state.options.materialMargin||0)/100; const comp=COMPLEXITY[state.options.complexity]||1; let screwCount=0,bandMl=0,compoundKg=0;
  allWalls().forEach(({wall,height,label})=>{ if(!wall.active) return; const net=wallNet(wall,height); if(net<=0) return; const faces=wall.type==='cloison'?[wall.face1,wall.face2]:[wall.face1]; const wallCladding=net*faces.length; cladding+=wallCladding; wallRows.push({label,type:wall.type==='cloison'?'Cloison':'Doublage',netOne:net,cladding:wallCladding,isolation:wall.isolation?.active});
    faces.forEach((face,i)=>{ const skins=face.doubleSkin?2:1; addPlate(materials,`${label} — Face ${i+1}`,face.plate,net,skins,R.plateLossWall,margin); screwCount += net*(R.screwsWall+(skins===2?R.screwsSecond:0)); });
    addFraming(materials,alerts,wall,height,label,net,margin);
    addIsolation(materials,sales,alerts,wall.isolation,net,label,margin,PROFILES[wall.framing.profile]?.width||48);
    if((wall.reinforcementQty||0)>0) sales.push({name:`Renfort(s) OSB — ${label}`,total:(+wall.reinforcementQty||0)*(+wall.reinforcementPrice||75),vat:vatFor('normal')});
    if(height>R.highHeight) sales.push({name:`Grande hauteur > 3,50 m — ${label}`,total:wallCladding*R.highHeightSale,vat:vatFor('normal')});
    let h=0; if(wall.type==='cloison'){ h=net*R.cloisonLabor; faces.forEach(f=>{if(f.doubleSkin)h+=net*R.secondSkinLabor;}); } else { const rate=wall.framing.system==='optima'?R.doublageOptimaLabor:(wall.isolation?.active?R.doublageClassicIsoLabor:R.doublageClassicNoIsoLabor); h=net*rate; if(wall.face1.doubleSkin)h+=net*R.secondSkinLabor; }
    if(wall.framing.doubledStuds) h*=1.5; if(wall.isolation?.active&&wall.isolation.semiRigid) h*=R.semiRigidLabor; h*=comp; labor.push({name:`Pose — ${label}`,hours:h}); laborHours+=h; bandMl+=wallCladding*R.finishBandWall; compoundKg+=wallCladding*R.finishCompoundWall;
  });
  state.pieces.forEach(p=>{ const c=p.ceiling; if(!c.active)return; const area=ceilingArea(p); if(area<=0)return; ceilingSurface+=area; cladding+=area; const skins=c.face.doubleSkin?2:1; addPlate(materials,`Plafond — ${p.name}`,c.face.plate,area,skins,c.type==='droit'?R.plateLossCeiling:R.plateLossRampant,margin); screwCount+=area*(R.screwsCeiling+(skins===2?R.screwsSecond:0)); addCeilingFrame(materials,alerts,p,area,margin); addIsolation(materials,sales,alerts,c.isolation,area,`Plafond — ${p.name}`,margin,999); let h=area*R.ceilingLabor+(skins===2?area*R.secondSkinLabor:0); if(c.isolation?.active&&c.isolation.semiRigid)h*=R.semiRigidLabor; h*=comp; labor.push({name:`Pose plafond — ${p.name}`,hours:h}); laborHours+=h; bandMl+=area*R.finishBandCeiling; compoundKg+=area*R.finishCompoundCeiling; if(c.type==='rampant')sales.push({name:`Plus-value rampant — ${p.name}`,total:area*R.rampantSale,vat:vatFor('normal')}); if(c.type==='rampant_complexe')sales.push({name:`Plus-value rampant complexe — ${p.name}`,total:area*R.rampantComplexSale,vat:vatFor('normal')}); });
  const screwsWithLoss=screwCount*(1+R.screwsLoss/100), screwBoxes=Math.ceil(screwsWithLoss/R.screwsBox); if(screwCount>0)materials.push({name:'Vis plaques',qty:Math.ceil(screwsWithLoss),unit:'u',order:`${screwBoxes} boîte(s) de ${R.screwsBox}`,unitPrice:.012,total:screwBoxes*R.screwsBox*.012,note:'25/m² murs, 18/m² plafond, +20/m² seconde peau, puis 10 % de perte.',vat:vatFor('normal')});
  if(bandMl>0) materials.push({name:'Bandes à joint — besoin interne',qty:bandMl,unit:'ml',order:rollOrder(bandMl),unitPrice:0,total:0,note:'Inclus dans le forfait de finition ; prix catalogue requis pour optimiser au coût réel.',vat:vatFor('normal')});
  if(compoundKg>0) materials.push({name:'Enduit à joint — besoin interne',qty:compoundKg,unit:'kg',order:potOrder(compoundKg),unitPrice:0,total:0,note:'Inclus dans le forfait de finition ; conditionnements 5/15/25 kg.',vat:vatFor('normal')});
  const finish=state.options.finish, finishPrice=R.finishPrices[finish]||0; if(finishPrice>0)sales.push({name:`Finition ${finishLabel(finish)}`,total:cladding*finishPrice,vat:vatFor('normal')}); if((finish==='pret_a_peindre'||finish==='soignee')&&state.options.impression)sales.push({name:'Impression',total:cladding*R.impression,vat:vatFor('normal')}); if(state.options.reprise)sales.push({name:'Reprise sur existant — forfait chantier',total:+state.options.reprisePrice||R.reprise,vat:vatFor('normal')}); if(state.options.access)sales.push({name:'Accès difficile — forfait chantier',total:+state.options.accessPrice||R.access,vat:vatFor('normal')}); if(state.options.cuts)sales.push({name:'Nombreuses découpes / spots',total:cladding*R.cutsSale,vat:vatFor('normal')}); state.options.extras.forEach(x=>sales.push({name:x.name||'Extra',total:(+x.qty||0)*(+x.price||0),vat:vatFor('normal')}));
  laborHours=labor.reduce((s,x)=>s+x.hours,0); const laborCost=laborHours*(+state.options.hourlyRate||0); const materialTotal=materials.reduce((s,x)=>s+(x.total||0),0); const saleTotal=sales.reduce((s,x)=>s+x.total,0); const baseLaborVat=vatFor('normal'); let vat=materials.reduce((s,x)=>s+(x.total||0)*(x.vat||0)/100,0)+sales.reduce((s,x)=>s+x.total*(x.vat||0)/100,0)+laborCost*baseLaborVat/100; const totalHT=materialTotal+saleTotal+laborCost; const totalTTC=totalHT+vat;
  allWalls().forEach(({wall,height,label})=>{ if(wall.active&&wall.isolation?.active&&!wall.isolation.validated)alerts.push(`⚠️ ${label} : isolation non validée par l’artisan.`); });
  return {surfaces:{cladding,ceiling:ceilingSurface},wallRows,materials,sales,labor,laborHours,laborCost,totalHT,vat,totalTTC,alerts:[...new Set(alerts)]}; }
function addPlate(arr,label,type,surface,skins,loss,margin){ const plate=PLATES[type]||PLATES.BA13; const purchaseM2=5.5+plate.surcharge; const required=surface*skins*(1+loss/100); const count=Math.ceil(required/3); const purchased=count*3; const saleUnit=purchaseM2*(1+margin); arr.push({name:`${plate.label} — ${label}${skins===2?' — double peau':''}`,qty:purchased,unit:'m²',order:`${count} plaque(s) 2,50 × 1,20`,unitPrice:saleUnit,total:purchased*saleUnit,note:`Surface après perte ${loss} %. Plus-value plaque appliquée sur quantité réellement achetée.`,vat:vatFor('normal')}); }
function addFraming(arr,alerts,w,height,label,net,margin){ const profile=PROFILES[w.framing.profile]||PROFILES['48/50']; if(w.type==='doublage'&&w.framing.system==='optima'){ const rows=Math.max(1,+w.framing.optimaRows||suggestRows(height)); addLinear(arr,`Fourrure F530 Optima — ${label}`,net*R.optima.furring,R.frameLoss,3,1.90,margin,'ml',vatFor('normal')); addLinear(arr,`Lisse Clip Optima — ${label}`,net*R.optima.clip,R.frameLoss,2.35,0,margin,'ml',vatFor('normal')); addUnit(arr,`Appuis Optima — ${label}`,net*R.optima.support,R.frameLoss,0,margin,vatFor('normal')); addUnit(arr,`Clés Optima — ${label}`,net*R.optima.key,R.frameLoss,0,margin,vatFor('normal')); addUnit(arr,`Fixations appuis Optima — ${label}`,net*R.optima.fixingPerRow*rows,R.frameLoss,0,margin,vatFor('normal')); alerts.push(`⚠️ ${label} : prix catalogue requis pour Lisse/Appui/Clé/fixations Optima.`); return; }
  const spacing=Math.max(.4,Math.min(.6,(+w.framing.spacingCm||60)/100)); const openingHoriz=(w.openings||[]).reduce((s,o)=>s+2*(+o.width||0)*(+o.qty||0),0); const openingStuds=(w.openings||[]).reduce((s,o)=>s+4*(+o.qty||0),0); const positions=Math.ceil((+w.length||0)/spacing)+1; const studs=(positions*(w.framing.doubledStuds?2:1)+openingStuds)*height; const rails=2*(+w.length||0)+openingHoriz; addLinear(arr,`Rails ${profile.label} — ${label}`,rails,R.frameLoss,3,profile.railPrice,margin,'ml',vatFor('normal')); addLinear(arr,`Montants ${profile.label} — ${label}`,studs,R.frameLoss,2.5,profile.studPrice,margin,'ml',vatFor('normal')); if(!profile.railPrice||!profile.studPrice)alerts.push(`⚠️ ${label} : prix catalogue manquant pour le profil ${profile.label}.`); }
function addCeilingFrame(arr,alerts,p,area,margin){ addLinear(arr,`Fourrures F47 plafond — ${p.name}`,area*1.8,R.frameLoss,3,1.90,margin,'ml',vatFor('normal')); alerts.push(`⚠️ Plafond ${p.name} : les accessoires/suspentes restent à résoudre depuis le catalogue réel. Aucun prix accessoire n’est inventé.`); }
function addIsolation(arr,sales,alerts,iso,surface,label,margin,profileWidth){ if(!iso?.active||surface<=0)return; const ref=ABAQUE.find(x=>x.id===iso.reference)||ABAQUE[0]; if(!ref)return; const loss=ref.kind==='blown'?R.isoBlownLoss:R.isoLoss; const base=(+iso.price||ref.prixAchatHtM2)*(iso.semiRigid?R.semiRigidMaterial:1); const qty=surface*(1+loss/100); arr.push({name:`Isolation — ${label} — ${ref.nom} ${iso.thickness||ref.epaisseurMm} mm`,qty,unit:'m²',order:`${fmt(qty)} m²`,unitPrice:base*(1+margin),total:qty*base*(1+margin),note:`Coût achat à marger. Perte ${loss} %${iso.semiRigid?' · semi-rigide ×1,20':''}.`,vat:vatFor('isolation')}); if((+iso.thickness||ref.epaisseurMm)>profileWidth)alerts.push(`⚠️ ${label} : isolant plus épais que le profil (${profileWidth} mm), sans blocage.`); if(iso.doubleLayer){ const ref2=ABAQUE.find(x=>x.id===iso.secondReference)||ref; const loss2=ref2.kind==='blown'?R.isoBlownLoss:R.isoLoss; const qty2=surface*(1+loss2/100); const base2=ref2.prixAchatHtM2*(iso.semiRigid?R.semiRigidMaterial:1); arr.push({name:`Isolation couche 2 — ${label} — ${ref2.nom} ${ref2.epaisseurMm} mm`,qty:qty2,unit:'m²',order:`${fmt(qty2)} m²`,unitPrice:base2*(1+margin),total:qty2*base2*(1+margin),note:'Deuxième couche réellement commandée et margée.',vat:vatFor('isolation')}); sales.push({name:`Pose isolation 2 couches${iso.crossed?' croisées':''} — ${label}`,total:surface*R.secondLayerSale*(iso.crossed?R.crossedLabor:1),vat:vatFor('isolation')}); }
  if(iso.pareVapeur)sales.push({name:`Pare-vapeur — ${label}`,total:surface*R.pareVapeur,vat:vatFor('isolation')}); if(iso.freinVapeur)sales.push({name:`Membrane hygrovariable — ${label}`,total:surface*R.freinVapeur,vat:vatFor('isolation')}); }
function addLinear(arr,name,theoretical,loss,bar,price,margin,unit,vat){ if(theoretical<=0)return; const withLoss=theoretical*(1+loss/100),bars=Math.ceil(withLoss/bar),purchased=bars*bar,salePrice=price*(1+margin); arr.push({name,qty:purchased,unit,order:`${bars} barre(s) de ${bar} m`,unitPrice:salePrice,total:purchased*salePrice,note:`Besoin ${fmt(theoretical)} ml + ${loss} % de perte.`,vat}); }
function addUnit(arr,name,theoretical,loss,price,margin,vat){ const final=Math.ceil(theoretical*(1+loss/100)); arr.push({name,qty:final,unit:'u',order:`${final} unité(s)`,unitPrice:price*(1+margin),total:final*price*(1+margin),note:`+${loss} % de perte. Prix catalogue requis si affiché à 0 €.`,vat}); }
function vatFor(kind){ if(!state.project.olderThan2Years)return 20; return kind==='isolation'?5.5:10; }
function finishLabel(k){ return ({bandes:'bandes',pret_a_peindre:'prêt à peindre',soignee:'soignée',aucune:'aucune'})[k]||k; }
function rollOrder(ml){ let left=Math.ceil(ml),parts=[]; [150,50,30].forEach(size=>{ const n=Math.floor(left/size); if(n){parts.push(`${n}×${size} m`);left-=n*size;} }); if(left>0)parts.push(`1×${left<=30?30:left<=50?50:150} m`); return parts.join(' + '); }
function potOrder(kg){ let left=Math.ceil(kg),parts=[]; [25,15,5].forEach(size=>{ const n=Math.floor(left/size); if(n){parts.push(`${n}×${size} kg`);left-=n*size;} }); if(left>0)parts.push(`1×${left<=5?5:left<=15?15:25} kg`); return parts.join(' + '); }

function onClick(e){ const wallHit=e.target.closest('[data-plan-wall]'); if(wallHit){ selected[wallHit.dataset.pieceid]=wallHit.dataset.planWall; renderWalls(); return; } const age=e.target.closest('[data-age]'); if(age){ state.project.olderThan2Years=age.dataset.age==='old'; save(); renderProject(); return; } const finish=e.target.closest('[data-finish]'); if(finish){ state.options.finish=finish.dataset.finish; if(!['pret_a_peindre','soignee'].includes(state.options.finish))state.options.impression=false; save(); renderOptions(); return; } const a=e.target.closest('[data-action]'); if(!a)return; const action=a.dataset.action; if(action==='add-piece')state.pieces.push(makePiece(state.pieces.length+1)); if(action==='remove-piece')state.pieces=state.pieces.filter(x=>x.id!==a.dataset.id); if(action==='add-simple')state.simpleWalls.push(makeSimpleWall(state.simpleWalls.length+1)); if(action==='remove-simple')state.simpleWalls=state.simpleWalls.filter(x=>x.id!==a.dataset.id); if(action==='add-opening'){ const w=getWallByScope(a.dataset.scope); w.openings.push({id:uid(),type:'porte',width:.9,height:2.1,qty:1}); } if(action==='remove-opening'){ const w=getWallByScope(a.dataset.scope); w.openings=w.openings.filter(x=>x.id!==a.dataset.openid); } if(action==='add-extra')state.options.extras.push({id:uid(),name:'Nouvel extra',qty:1,price:0}); if(action==='remove-extra')state.options.extras=state.options.extras.filter(x=>x.id!==a.dataset.id); save(); render(); }
function onInput(e){ const t=e.target; if(t.dataset.path){ setPath(state,t.dataset.path,valueOf(t)); save(); return; } if(t.dataset.piece){ const p=state.pieces.find(x=>x.id===t.dataset.piece); setPath(p,t.dataset.pkey,valueOf(t)); if(['length','width'].includes(t.dataset.pkey))syncPieceWalls(p); save(); if(step===1)renderWorks(); return; } if(t.dataset.simple){ const w=state.simpleWalls.find(x=>x.id===t.dataset.simple); setPath(w,t.dataset.skey,valueOf(t)); save(); return; } if(t.dataset.wall){ const w=getWallByScope(t.dataset.wall); setPath(w,t.dataset.wkey,valueOf(t)); if(t.dataset.wkey==='isolation.reference'){const ref=ABAQUE.find(x=>x.id===t.value); if(ref){w.isolation.price=ref.prixAchatHtM2;w.isolation.thickness=ref.epaisseurMm;if(!w.isolation.secondReference)w.isolation.secondReference=ref.id;}} if(t.dataset.wkey==='isolation.active'&&w.isolation.active&&!w.isolation.reference){const ref=ABAQUE[0]; if(ref){w.isolation.reference=ref.id;w.isolation.price=ref.prixAchatHtM2;w.isolation.thickness=ref.epaisseurMm;w.isolation.secondReference=ref.id;}} save(); if(step===2)renderWalls(); return; } if(t.dataset.open){ const w=getWallByScope(t.dataset.scope),o=w.openings.find(x=>x.id===t.dataset.open); o[t.dataset.okey]=valueOf(t); save(); if(step===2)renderWalls(); return; } if(t.dataset.ceiling){ const p=state.pieces.find(x=>x.id===t.dataset.ceiling); setPath(p.ceiling,t.dataset.ckey,valueOf(t)); if(t.dataset.ckey==='isolation.reference'){const ref=ABAQUE.find(x=>x.id===t.value); if(ref){p.ceiling.isolation.price=ref.prixAchatHtM2;p.ceiling.isolation.thickness=ref.epaisseurMm;}} save(); if(step===3)renderCeilings(); return; } if(t.dataset.extra){ const x=state.options.extras.find(y=>y.id===t.dataset.extra); x[t.dataset.ekey]=valueOf(t); save(); return; } }

function allWalls(){ const out=[]; state.pieces.forEach(p=>{syncPieceWalls(p); p.walls.forEach(w=>out.push({wall:w,height:+p.height||0,label:`${p.name} — ${w.label}`}));}); state.simpleWalls.forEach(w=>out.push({wall:w,height:+w.height||0,label:w.label})); return out; }
function syncPieceWalls(p){ if(!p.walls||p.walls.length!==4)p.walls=[wallBase('A','Mur A (face)',p.length),wallBase('B','Mur B (droite)',p.width),wallBase('C','Mur C (fond)',p.length),wallBase('D','Mur D (gauche)',p.width)]; p.walls.forEach(w=>{ if(w.id==='A'||w.id==='C')w.length=+p.length||0; else w.length=+p.width||0; ensureWall(w); }); if(!p.ceiling)p.ceiling={active:true,type:'droit',manualArea:null,face:faceDefault(),isolation:isoDefault()}; if(!p.ceiling.face)p.ceiling.face=faceDefault(); if(!p.ceiling.isolation)p.ceiling.isolation=isoDefault(); }
function ensureWall(w){ if(!w.framing)w.framing=framingDefault(); if(!w.face1)w.face1=faceDefault(); if(!w.face2)w.face2=faceDefault(); if(!w.isolation)w.isolation=isoDefault(); if(!w.openings)w.openings=[]; if(w.reinforcementPrice==null)w.reinforcementPrice=75; return w; }
function ensureIso(w){ ensureWall(w); return w.isolation; } function ensureFace(w,k){ensureWall(w);return w[k];}
function getWallByScope(scope){ const [kind,id]=scope.split(':'); if(kind==='piece'){ const p=state.pieces.find(x=>x.id===id); return p.walls.find(w=>w.id===selected[id]||w.id==='A'); } return state.simpleWalls.find(w=>w.id===id); }
function wallNet(w,height){ const gross=Math.max(0,+w.length||0)*Math.max(0,+height||0); const openings=(w.openings||[]).reduce((s,o)=>s+Math.max(0,+o.width||0)*Math.max(0,+o.height||0)*Math.max(0,+o.qty||0),0); return Math.max(0,gross-openings); }
function ceilingArea(p){ return p.ceiling.type==='droit'?Math.max(0,+p.length||0)*Math.max(0,+p.width||0):Math.max(0,+p.ceiling.manualArea||(+p.length||0)*(+p.width||0)); }
function suggestRows(h){ if(API.getSuggestedOptimaRows)return API.getSuggestedOptimaRows(+h||0); return Math.max(1,Math.ceil((+h||0)/1.35)-1); }
function planSvg(p,sel){ const L=Math.max(.1,+p.length||.1),W=Math.max(.1,+p.width||.1),scale=Math.min(420/L,220/W),rw=L*scale,rh=W*scale,x=(520-rw)/2,y=(310-rh)/2,coords={A:[x,y,x+rw,y],B:[x+rw,y,x+rw,y+rh],C:[x+rw,y+rh,x,y+rh],D:[x,y+rh,x,y]}; let lines=''; p.walls.forEach(w=>{const c=coords[w.id],cl=!w.active?'wall-off':w.type==='cloison'?'wall-cloison':'wall-doublage',mid=[(c[0]+c[2])/2,(c[1]+c[3])/2]; lines+=`<g data-plan-wall="${w.id}" data-pieceid="${p.id}" class="${sel===w.id?'selected-wall':''}"><line class="wall-hit" x1="${c[0]}" y1="${c[1]}" x2="${c[2]}" y2="${c[3]}"></line><line class="wall-line ${cl}" x1="${c[0]}" y1="${c[1]}" x2="${c[2]}" y2="${c[3]}"></line><text class="wall-label" x="${mid[0]+(w.id==='B'?15:w.id==='D'?-15:0)}" y="${mid[1]+(w.id==='A'?-12:w.id==='C'?22:4)}" text-anchor="middle">${w.id}</text>${openingSvg(w,c)}</g>`;}); return `<svg viewBox="0 0 520 310"><rect x="${x}" y="${y}" width="${rw}" height="${rh}" fill="#fff" stroke="#cbd5e1"/>${lines}<text x="260" y="22" text-anchor="middle" font-size="12">L : ${fmt(L)} m</text><text x="18" y="155" font-size="12" transform="rotate(-90 18 155)" text-anchor="middle">l : ${fmt(W)} m</text><text x="260" y="295" text-anchor="middle" font-size="12">H : ${fmt(p.height)} m</text></svg>`; }
function openingSvg(w,c){ const os=(w.openings||[]).flatMap(o=>Array.from({length:Math.min(8,+o.qty||0)},()=>o)); if(!os.length)return''; const horiz=Math.abs(c[2]-c[0])>0,len=Math.hypot(c[2]-c[0],c[3]-c[1]); return os.map((o,i)=>{const t=(i+1)/(os.length+1),cx=c[0]+(c[2]-c[0])*t,cy=c[1]+(c[3]-c[1])*t,ww=Math.max(15,Math.min(len*.25,(+o.width||.5)/Math.max(.2,+w.length||1)*len)),klass=o.type==='porte'?'opening-door':'opening-window'; return horiz?`<line class="${klass}" x1="${cx-ww/2}" y1="${cy}" x2="${cx+ww/2}" y2="${cy}"/>`:`<line class="${klass}" x1="${cx}" y1="${cy-ww/2}" x2="${cx}" y2="${cy+ww/2}"/>`;}).join(''); }
function valueOf(t){ if(t.type==='checkbox')return t.checked; if(t.type==='number')return t.value===''?null:+t.value; if(t.value==='true')return true; if(t.value==='false')return false; return t.value; }
function setPath(obj,path,val){ const ps=path.split('.'); let x=obj; for(let i=0;i<ps.length-1;i++){x=x[ps[i]]||(x[ps[i]]={});} x[ps.at(-1)]=val; }
function fmt(n){ return Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:2}); } function eur(n){ return Number(n||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'}); } function esc(s){ return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function toast(msg){ const e=document.createElement('div');e.className='alert ok toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),1600); }
