(function(global){
"use strict";
/* SpeedArti Plaquiste — rules-only demo bundle v1.3.0.
   No legacy calculator, no hidden catalogue price, no silent fallback. */
const rules = Object.freeze({
  version: 'plaquiste-business-2026-08-19-v1.3.0',
  plaques: { largeurCommercialeM:1.20, perteMurPct:7, pertePlafondPct:10, perteRampantPct:12,
    surchargeAchatHtM2:Object.freeze({BA13:0,hydro:0.85,phonique:1.35,feu:2.00,habito:3.20}) },
  ossature: { pertePct:5, ouvertureMontantsTouteHauteur:4, ouvertureProfilsHorizontauxParLargeur:2,
    profilsLargeurMm:Object.freeze([48,70,90,100]),
    seuilsHauteurM:Object.freeze({m48Simple60:2.50,m48Simple40:2.80,m48Double60:3.05,m48Double40:3.45,maxAuto:4.15}) },
  vis: { premierePeauMurParM2:25, premierePeauPlafondParM2:18, secondePeauParM2:20, pertePct:10, boiteUnites:500 },
  finitions: { bandeMurMlM2:1.8, bandePlafondMlM2:2.2, enduitMurKgM2:0.5, enduitPlafondKgM2:0.6,
    prixVenteHtM2:Object.freeze({aucune:0,bandes:5,pret_a_peindre:9,soignee:13}), impressionHtM2:5 },
  isolation: { pertePanneauxRouleauxPct:10, perteSoufflePct:3, semiRigideCoefMatiere:1.20,
    semiRigideCoefMainOeuvre:1.20, secondeCouchePoseHtM2:3, poseCroiseeCoefMainOeuvre:1.15,
    pareVapeurPrixVenteHtM2:3.50, freinVapeurPrixVenteHtM2:5.00 },
  optima: { espacementVerticalRangeeM:1.35, fourrureF530MlM2:1.8, lisseClipMlM2:0.9,
    appuiUniteM2:0.75, cleUniteM2:0.75, fixationsUniteM2ParRangee:2 },
  plafondDroit: { fourrureMlM2:1.67, suspenteUniteM2:1.45, corniereMlM2:0.42,
    eclisseUniteM2:0.20, cavalierConnecteurUniteM2:0.35 },
  mainOeuvre: { cloisonHParM2:0.35, doublageOptimaHParM2:0.40, doublageClassiqueSansIsolantHParM2:0.26,
    doublageClassiqueAvecIsolantHParM2:0.32, plafondDroitHParM2:0.40, secondePeauHParM2:0.05,
    montantsDoublesCoef:1.50, complexiteCoef:Object.freeze({simple:0.90,moyenne:1,complexe:1.30}) },
  optionsDirectes: { repriseExistantHt:150, accesDifficileHt:450, seuilGrandeHauteurM:3.50,
    grandeHauteurHtM2:4, nombreusesDecoupesSpotsHtM2:2, rampantHtM2:5, rampantComplexeHtM2:11,
    angleSortantHtMl:7, renfortOsbHtUnite:75 }
});
const abaque = [
    { id: 'abaque-ldv-45', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 45, prixAchatHtM2: 3.28, usage: 'Cloison', kind: 'panel_roll' },
    { id: 'abaque-ldr-45', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 45, prixAchatHtM2: 4.92, usage: 'Cloison coupe-feu/phonique', kind: 'panel_roll' },
    { id: 'abaque-fdb-45', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 45, prixAchatHtM2: 6.56, usage: 'Cloison', kind: 'panel_roll' },
    { id: 'abaque-ldv-70', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 70, prixAchatHtM2: 4.10, usage: 'Doublage', kind: 'panel_roll' },
    { id: 'abaque-ldr-70', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 70, prixAchatHtM2: 5.74, usage: 'Doublage', kind: 'panel_roll' },
    { id: 'abaque-fdb-70', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 70, prixAchatHtM2: 8.20, usage: 'Doublage', kind: 'panel_roll' },
    { id: 'abaque-ldv-90', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 90, prixAchatHtM2: 4.92, usage: 'Cloison R90', kind: 'panel_roll' },
    { id: 'abaque-ldr-90', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 90, prixAchatHtM2: 6.56, usage: 'Phonique', kind: 'panel_roll' },
    { id: 'abaque-fdb-90', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 90, prixAchatHtM2: 9.84, usage: 'Phonique', kind: 'panel_roll' },
    { id: 'abaque-ldv-100', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 100, prixAchatHtM2: 5.74, usage: 'ITI', kind: 'panel_roll' },
    { id: 'abaque-ldr-100', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 100, prixAchatHtM2: 7.38, usage: 'ITI', kind: 'panel_roll' },
    { id: 'abaque-fdb-100', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 100, prixAchatHtM2: 11.48, usage: 'ITI', kind: 'panel_roll' },
    { id: 'abaque-ldv-120', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 120, prixAchatHtM2: 6.56, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-ldr-120', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 120, prixAchatHtM2: 8.20, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-fdb-120', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 120, prixAchatHtM2: 13.12, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-ldv-140', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 140, prixAchatHtM2: 7.38, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-ldr-140', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 140, prixAchatHtM2: 9.02, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-fdb-140', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 140, prixAchatHtM2: 14.76, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-ldv-160', famille: 'Minéral', nom: 'Laine de verre', epaisseurMm: 160, prixAchatHtM2: 8.20, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-ldr-160', famille: 'Minéral', nom: 'Laine de roche', epaisseurMm: 160, prixAchatHtM2: 9.84, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-fdb-160', famille: 'Naturel', nom: 'Fibre de bois', epaisseurMm: 160, prixAchatHtM2: 16.40, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-pse-blanc-80', famille: 'Synthétique', nom: 'PSE blanc', epaisseurMm: 80, prixAchatHtM2: 7.38, usage: 'ITE', kind: 'panel_roll' },
    { id: 'abaque-pse-graphite-100', famille: 'Synthétique', nom: 'PSE graphité', epaisseurMm: 100, prixAchatHtM2: 10.66, usage: 'ITE', kind: 'panel_roll' },
    { id: 'abaque-xps-80', famille: 'Synthétique', nom: 'XPS', epaisseurMm: 80, prixAchatHtM2: 13.12, usage: 'Soubassement', kind: 'panel_roll' },
    { id: 'abaque-pur-pir-80', famille: 'Synthétique', nom: 'PUR/PIR', epaisseurMm: 80, prixAchatHtM2: 18.04, usage: 'Toiture terrasse', kind: 'panel_roll' },
    { id: 'abaque-ouate-100', famille: 'Naturel', nom: 'Ouate de cellulose', epaisseurMm: 100, prixAchatHtM2: 9.02, usage: 'Combles', kind: 'panel_roll' },
    { id: 'abaque-chanvre-100', famille: 'Naturel', nom: 'Chanvre', epaisseurMm: 100, prixAchatHtM2: 12.30, usage: 'ITI', kind: 'panel_roll' },
    { id: 'abaque-lin-100', famille: 'Naturel', nom: 'Lin', epaisseurMm: 100, prixAchatHtM2: 13.12, usage: 'ITI', kind: 'panel_roll' },
    { id: 'abaque-liege-40', famille: 'Naturel', nom: 'Liège expansé', epaisseurMm: 40, prixAchatHtM2: 19.68, usage: 'ITE/sol', kind: 'panel_roll' },
    { id: 'combles-souffle-ldv-200', famille: 'Minéral', nom: 'Laine de verre soufflée', epaisseurMm: 200, prixAchatHtM2: 8, usage: 'Combles soufflés', kind: 'blown', rApprox: 5.0 },
    { id: 'combles-souffle-ldv-300', famille: 'Minéral', nom: 'Laine de verre soufflée', epaisseurMm: 300, prixAchatHtM2: 11, usage: 'Combles soufflés', kind: 'blown', rApprox: 7.5 },
    { id: 'combles-souffle-ldv-400', famille: 'Minéral', nom: 'Laine de verre soufflée', epaisseurMm: 400, prixAchatHtM2: 14, usage: 'Combles soufflés', kind: 'blown', rApprox: 10.0 },
    { id: 'combles-souffle-ldr-200', famille: 'Minéral', nom: 'Laine de roche soufflée', epaisseurMm: 200, prixAchatHtM2: 10, usage: 'Combles soufflés', kind: 'blown', rApprox: 5.4 },
    { id: 'combles-souffle-ldr-300', famille: 'Minéral', nom: 'Laine de roche soufflée', epaisseurMm: 300, prixAchatHtM2: 13, usage: 'Combles soufflés', kind: 'blown', rApprox: 8.1 },
    { id: 'combles-souffle-ouate-300', famille: 'Naturel', nom: 'Ouate de cellulose soufflée', epaisseurMm: 300, prixAchatHtM2: 15, usage: 'Combles soufflés', kind: 'blown', rApprox: 7.5 },
    { id: 'combles-souffle-ouate-400', famille: 'Naturel', nom: 'Ouate de cellulose soufflée', epaisseurMm: 400, prixAchatHtM2: 19, usage: 'Combles soufflés', kind: 'blown', rApprox: 10.0 },
    { id: 'combles-rouleau-ldv-200', famille: 'Minéral', nom: 'Laine de verre rouleau', epaisseurMm: 200, prixAchatHtM2: 9, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 5.0 },
    { id: 'combles-rouleau-ldv-240', famille: 'Minéral', nom: 'Laine de verre rouleau', epaisseurMm: 240, prixAchatHtM2: 11, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 6.0 },
    { id: 'combles-rouleau-ldv-300', famille: 'Minéral', nom: 'Laine de verre rouleau', epaisseurMm: 300, prixAchatHtM2: 14, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 7.5 },
    { id: 'combles-rouleau-ldr-200', famille: 'Minéral', nom: 'Laine de roche rouleau', epaisseurMm: 200, prixAchatHtM2: 12, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 5.4 },
    { id: 'combles-rouleau-ldr-300', famille: 'Minéral', nom: 'Laine de roche rouleau', epaisseurMm: 300, prixAchatHtM2: 16, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 8.1 },
    { id: 'combles-rouleau-fdb-200', famille: 'Naturel', nom: 'Fibre de bois rouleau', epaisseurMm: 200, prixAchatHtM2: 22, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 5.2 },
    { id: 'combles-rouleau-fdb-240', famille: 'Naturel', nom: 'Fibre de bois rouleau', epaisseurMm: 240, prixAchatHtM2: 25, usage: 'Combles rouleaux', kind: 'panel_roll', rApprox: 6.3 },
];
function getSuggestedOptimaRows(heightM){ const h=Math.max(0,Number(heightM)||0); return Math.max(1,Math.ceil(h/rules.optima.espacementVerticalRangeeM)-1); }
function getPlaquistePlateLossPct(ceilingType){ if(!ceilingType)return rules.plaques.perteMurPct; return ceilingType==='droit'?rules.plaques.pertePlafondPct:rules.plaques.perteRampantPct; }
global.SpeedArtiPlaquisteReal={rules,abaque,getSuggestedOptimaRows,getPlaquistePlateLossPct};
})(typeof window!=="undefined"?window:globalThis);
