(function(){
function mat(id,nom,prix,categorie='Forfait',qte=1,unite='forfait'){return{article_id:id,nom,categorie,quantite_theorique:qte,quantite_avec_perte:qte,quantite_finale:qte,unite,prix_unitaire_ht:prix,total_ht:prix*qte,stock_disponible:0,a_commander:unite==='forfait'?0:qte,coef_perte_applique:1}}
const r2=n=>Math.round(n*100)/100;
function calculate(d){if(!d||d.metier!=='plombier')throw new Error('Le métier Plombier est requis');if(!d.nom_calcul)throw new Error('Le nom du calcul est requis');return(d.options?.type_projet||'installation_complete')==='petits_travaux'?petits(d):complete(d)}
function petits(d){
const o=d.options||{},nature=o.nature_intervention||'',taux=o.taux_horaire??52,ouv=o.nb_ouvriers??1;let ms=[],h=0,lib='Intervention plomberie';
if(nature==='fuite'){lib='Recherche de fuite';ms.push(mat('fuite_visite','Visite diagnostic fuite',150));const t=o.type_recherche_fuite;if(t==='camera')ms.push(mat('fuite_camera','Caméra endoscopique',180));else if(t==='demolition')ms.push(mat('fuite_demolition','Démolition + recherche',250));else if(t)ms.push(mat('fuite_'+t,'Recherche ('+t+')',80));h=2}
else if(nature==='chauffe_eau'){lib='Intervention chauffe-eau';const map={reparation:{p:120,h:2,n:'Réparation / nettoyage chauffe-eau'},changement_200l_elec:{p:380,h:3,n:'Changement chauffe-eau 200L élec'},changement_300l_elec:{p:450,h:3.5,n:'Changement chauffe-eau 300L élec'},ballon_thermo_air_ext:{p:850,h:4,n:'Ballon thermodynamique'},ballon_thermo_groupe_ext:{p:950,h:5,n:'Groupe extérieur / sortie toit'}};const c=map[o.type_chauffe_eau_intervention]||map.reparation;ms.push(mat('ce_'+(o.type_chauffe_eau_intervention||'reparation'),c.n,c.p,'Fournitures'));h=c.h}
else if(nature==='debouchage'){lib='Forfait débouchage';ms.push(mat('debouchage','Forfait débouchage (tout compris)',180));h=1}
else if(nature==='remplacement'){const els=Array.isArray(o.elements_sanitaires_remplaces)&&o.elements_sanitaires_remplaces.length?o.elements_sanitaires_remplaces:['wc'];const prix={wc:250,douche:400,baignoire:500,meuble_vasque:350,lave_main:200,evier:300};const hh={wc:3,douche:6,baignoire:5,meuble_vasque:3,lave_main:3,evier:3};const cg=o.gamme==='eco'?.7:o.gamme==='premium'?1.6:1;const labels=[];els.forEach(el=>{ms.push(mat('rempl_'+el,'Remplacement '+el+' (gamme '+(o.gamme||'standard')+')',(prix[el]||250)*cg,'Sanitaires'));let x=hh[el]||3;if(el==='douche'&&o.type_douche==='italienne')x*=1.4;h+=x;labels.push('Remplacement '+el)});if(o.norme_handicapee&&els.includes('wc'))ms.push(mat('pmr_supplement','Supplément norme PMR',80,'Sanitaires'));lib=labels.join(' + ')||'Remplacement'}
const fs={forfait_demolition:[350,'Forfait démolition'],forfait_deplacement:[45,'Forfait déplacement'],forfait_platrerie:[200,'Petits travaux plâtrerie'],forfait_pose:[150,'Forfait pose'],forfait_traversee:[180,'Traversée plancher / mur'],forfait_renovation:[300,'Forfait rénovation'],forfait_raccordement:[120,'Raccordement sur existant']};Object.entries(fs).forEach(([k,[p,l]])=>{if(o[k])ms.push(mat(k,l,p,'Forfaits'))});if(o.forfait_depose){ms.push(mat('forfait_depose','Dépose existant',120,'Forfaits'));h+=1}
const mh=ms.reduce((s,m)=>s+m.total_ht,0),mo=h*taux,ht=mh+mo,tva=r2(ht*.2);return result(ms,h,ouv,taux,lib,mh,mo,ht,tva,['État source reproduit : la durée saisie dans le Wizard n’est pas encore la source de calcul dans ce moteur de référence.','Catalogue, stock et règles finales Guillaume non raccordés dans cette v0.1.0.'])}
function complete(d){
const o=d.options||{},x=d.dimensions||{},nLav=x.nombre_lavabos??1,nDou=x.nombre_douches??1,nBai=x.nombre_baignoires??0,nWC=x.nombre_wc??1,nEv=x.nombre_eviers??1,nLL=x.nombre_lave_linge??1,nLV=x.nombre_lave_vaisselle??0,total=nLav+nDou+nBai+nWC+nEv+nLL+nLV,cg=o.gamme==='eco'?.7:o.gamme==='premium'?1.6:1,tuy=o.type_tuyau||'PER',ds=x.distance_chauffe_eau_sdb??5,dc=x.distance_chauffe_eau_cuisine??8,ef=total*8,ec=(nLav+nDou+nBai+nEv)*8+ds+dc,evac=total*5,loss=1.05;const ms=[];
const tn=String(tuy).toLowerCase()==='cuivre'?'cuivre':String(tuy).toLowerCase()==='multicouche'?'multicouche':'PER';
ms.push({...mat('tuyau_'+String(tuy).toLowerCase(),'Tuyau '+tn+' Ø16',0,'Plomberie',Math.ceil((ef+ec)*loss),'ml'),quantite_theorique:ef+ec,quantite_avec_perte:(ef+ec)*loss,coef_perte_applique:loss});
ms.push({...mat('raccord_'+String(tuy).toLowerCase(),'Raccords et coudes',0,'Plomberie',Math.ceil(total*6*1.1),'unité'),quantite_theorique:total*6,quantite_avec_perte:total*6*1.1,coef_perte_applique:1.1});ms.push(mat('robinet_arret','Robinet arrêt équerre',0,'Plomberie',total,'unité'));
const P={baignoire:450,wc_suspendu:320,wc_poser:120,douche_italienne:380,douche_extra_plat:220,douche_bac:150,evier_inox:180,evier_resine:250,evier_ceramique:320};
if(nBai>0){const t=o.type_baignoire||'droite',p=t==='angle'?650:t==='asymetrique'?550:P.baignoire;ms.push(mat('baignoire','Baignoire '+t+' avec robinetterie',p*cg,'Sanitaires',nBai,'unité'))}
if(nWC>0){const t=o.type_wc||'poser',p=(t==='suspendu'?P.wc_suspendu:P.wc_poser)+(o.norme_handicapee?80:0);ms.push(mat('wc','WC '+t+(o.norme_handicapee?' PMR':''),p*cg,'Sanitaires',nWC,'unité'))}
if(nDou>0){const t=o.type_douche||'bac',man=+o.prix_bac_douche_manuel||0;let p=man||P.douche_bac;if(!man&&t==='italienne')p=P.douche_italienne;if(!man&&t==='extra_plat')p=P.douche_extra_plat;p+=(o.douche_avec_mitigeur?80:0)+(o.douche_avec_colonne?120:0)+(o.douche_avec_paroi?200:0);ms.push(mat('douche','Douche '+t,p*cg,'Sanitaires',nDou,'unité'))}
if(nEv>0){const t=o.type_evier||'inox',p=P['evier_'+t]||P.evier_inox,c=o.config_evier||'simple_bac_a_poser',sup=(c.includes('double')?80:0)+(c.includes('sous_plan')?50:0);ms.push(mat('evier','Évier '+t+(c.includes('double')?' double bac':'')+(c.includes('sous_plan')?' sous-plan':''),(p+sup)*cg,'Sanitaires',nEv,'unité'))}
if(o.adoucisseur)ms.push(mat('adoucisseur',"Adoucisseur d'eau",600*cg,'Équipements',1,'unité'));
const f={forfait_demolition:350,forfait_deplacement:45,forfait_platrerie:200,forfait_raccordement:150,forfait_traversee:120,forfait_renovation:400,acces_difficile:100,limiteur_pression:86,boucle_ecs:400,pompe_relevage:650,ventilation_wc:107};Object.entries(f).forEach(([k,p])=>{if(o[k])ms.push(mat(k,k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()),p,'Forfaits'))});
const cdiff=o.acces_difficile?1.3:1,cdou=o.type_douche==='italienne'?1.4:1,htuy=(ef+ec+evac)*.15,hsan=total*2*cdou,h=(htuy+hsan)*cdiff,taux=o.taux_horaire??52,ouv=o.nb_ouvriers??1,mh=ms.reduce((s,m)=>s+m.total_ht,0),mo=h*taux,ht=mh+mo,tva=r2(ht*.2);const rr=result(ms,h,ouv,taux,'Installation complète',mh,mo,ht,tva,['État source reproduit : les prix catalogue de tuyaux/raccords/robinets restent à 0 dans cette démo autonome.','État source reproduit : les valeurs absentes peuvent encore utiliser les anciens défauts du calculateur.','Deux décisions Guillaume restent volontairement hors moteur : réseau seul sans sanitaire et lignes non classées de l’annexe 1.']);rr.surfaces.detail_par_face={appareils:total,EF_ml:ef,EC_ml:ec,evac_ml:evac};rr.main_oeuvre.decomposition=[{poste:'Pose tuyauterie',temps_heures:htuy*cdiff},{poste:'Pose sanitaires',temps_heures:hsan*cdiff}];return rr}
function result(ms,h,ouv,taux,lib,mh,mo,ht,tva,w){return{surfaces:{totale:0,nette:0,avec_pertes:0,detail_par_face:{}},materiaux:ms,main_oeuvre:{temps_estime_heures:Math.round((h/ouv)*10)/10,decomposition:[{poste:lib,temps_heures:h}],taux_horaire:taux,nombre_ouvriers:ouv,cout_total:mo},totaux:{materiaux_ht:r2(mh),main_oeuvre_ht:r2(mo),total_ht:r2(ht),tva:r2(tva),total_ttc:r2(ht+tva)},stock_status:{disponible:false,articles_manquants:ms.filter(m=>m.a_commander>0)},recommandations:[],alertes:w||[]}}
window.SpeedArtiPlombierCurrent={calculate};
})();